### ISSUE TITLE
can i use this to host a multi-algorthimical simulation model of society in 2020

### ISSUE THREAD

**Issue by DenisBobrovskiy** [aleksimart/goserver#4]
me and my company are trying to simulate society in 2020 to predict when white heterosexual males will finally be prosecuted for existing and we belive ur server technology is essential for out succ sess. U can contact us at https://1man1jar.com

**Comment by DenisBobrovskiy** [comment]
WTF

**Comment by DenisBobrovskiy** [comment]
DID U JUST FUCKING ASSIGN ME TO FIX THE FUCKING ISSUE ON UR FUCKING SERVER

**Comment by DenisBobrovskiy** [comment]
u sneaky piece of shit

**Comment by aleksimart** [comment]
Did you fix it yet?

**Comment by DenisBobrovskiy** [comment]
fuck pls boss

**Comment by aleksimart** [comment]
Only post marriage
